### ISSUE TITLE
Differentiate failure cases

### ISSUE THREAD

**Issue by jdpedrie** [Ziptastic/ziptastic-php#3]
Invalid API key should not have the same result as an invalid zip code, etc.

**Comment by daspecster** [comment]
Also, the unauthorized response is a 401. I should list these on the website docs.

**Comment by jdpedrie** [comment]
Invalid API key should throw an exception. Invalid zip code should return false (or maybe null?)

**Comment by daspecster** [comment]
So there's a difference between invalid zipcode and zipcode that's not in the database. It would be hard to statically check for a valid/invalid zipcode since in different countries the format varies a decent amount.  Using the API responses is probably the best bet. Maybe turning those into a PHP exception that's descriptive.   Also it would be good to have a PHP exception for if the server is unresponsive.

I would think it might be something like this...
- 404 from API ->  PHP exception ZipCodeNotFound
- 401 from API -> PHP exception UnrecognizedAPIKey or something liket hat
- timeout from API -> PHP exception ZiptasticTimeout.

Maybe different exception names but something like that.

**Comment by thomasfeduk** [comment]
The regarding the concern of ambiguity with there being no way to distinguish if the Ziploc is simply mistyped/incorrectly cased, or if a successful call was made, but the zip code just wasn't found/was malformed:

I personally put in a vote for the following:
- 400: If no api key is specified/incorrectly formatted/request doesn't meet the expected format
  - We use 400 whenever a client message structure doesn't meet specifications, but yet reached a live api that talks back
- 401: API key not matched/valid/expired/invalid, although properly formatted
  - This lets you know to check your key, but that the request and supply of the key was done correctly
- 402: Payment Required
  - Client has exceeded the number of API calls/lookpus within a day and should update their plan
- 404: Zip code not found
  - Same as it is currently
- 406: Not Acceptable
  - While usually refers to output via a header condition, this may be an http code to use to indicate a valid message format was received with a valid api key, but just a malformed **lookup** value was specified (such as a 4 digit zip etc).
  - This makes it easy to distinguish between a bad zip, vs a zip thats not found, although as mentioned it may be too much time on your dev's portion to be able to inspect/process proper formats for acceptable input based on region.

Quick reference to the HTTP RFCs:
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error

---

A secondary option (which we use in our platform), but may not be applicable here, is to deviate from the standard http-code-only response and use an http code as base, but include in the json return an object called 'error' if _any_ error was present with an element called **code** and another called **message**. The receiving client then knows if an error element exists in the top level of the return, there was a problem.

This would allow for very fine-grained error codes to describe all possible conditions. Our platform uses over 80 codes presently and it allows for some very dynamic behavior from our client apps.

**Comment by jdpedrie** [comment]
> 402: Payment Required
> Client has exceeded the number of API calls/lookpus within a day and should update their plan

[429](https://httpstatuses.com/429) may be a better fit for this case?

Besides that I think you're right, but I don't know the difficulty of actually modifying the API and maintaining compatibility with other clients and users.

**Comment by thomasfeduk** [comment]
I originally planned on using 429 but it seems Google themselves are using 402 for when their clients exceed requests. Generally when a company that large uses something even in a non intended manner, it quickly starts to become adopted as a standard industry wide.

**Comment by daspecster** [comment]
Hey @jdpedrie, I know your schedule has been like mine haha. Do you think we could take a look at this more next week and include @austinkregel as well?

**Comment by jdpedrie** [comment]
Yep, next week should be much better.

**Comment by austinkregel** [comment]
Honestly, I disagree with using the 402 code. Even if Google uses it, it doesn't go with what the HTTP codes were really meant for. I feel like using a 429 code would be best.

 I feel that a 402 code would be for when the client has an account with a balance or when their account has been closed. The 429 error should be for when the quota is hit. If the quota is about to reset and the user hits the limit, they shouldn't be told to upgrade if they just have a surge in users.

I feel we should stick with using a 429 code for quotas, and 402 for when an account has gone unpaid or when it's closed orsomeone is using old credentials. 

Other than that @daspecster this weekend would work best for me.

**Comment by jdpedrie** [comment]
Rate Limiting and Quotas are not necessarily the same thing. You can get rate limited but still have a million requests left in your plan. Ziptastic doesn't rate limit (as far as I know now), but it's not inconceivable that it would in the future, so reserving 429 for it's _best_ use makes good sense to me.

There's not an exact match for the case we're talking about, but @thomasfeduk made a good case for 402, and combined with the rate limiting I think that's the most forward-compatible option.

**Comment by daspecster** [comment]
@austinkregel, @jdpedrie I think I can give some clarity here. I should have explained how the API works currently.

429
Right now the API does return a 429 when you've used more than your quota for the day.

401
It also returns 401 if the API key is invalid or not provided.

402
I'm planning on adding 402 for when you have a valid API key but your account isn't paid up.  Right now  there are some accounts where their CC expires and then I have contact them and sort it out etc...
However I need to figure out a process for that.

Essentially what I'm thinking is that we just pass through the HTTP response code that the API returns.
