### ISSUE TITLE
Zipcode: 95531 returning empty timezone.

### ISSUE THREAD

**Issue by devtayls** [Ziptastic/ziptastic-php#6]
The zip code should return the UTC-8 (Pacific Time Zone) and UTC-7 (Pacific Daylight Time).

![image](https://user-images.githubusercontent.com/16793430/35695143-e30ec44a-0740-11e8-990b-6cba096242b3.png)

**Comment by daspecster** [comment]
Thanks for reporting!

I doubt I will be able to return multiple TZs. There is probably only on TZ for the lat/long provided. However I understand a postal code crossing TZs as well.

If you're taking input from a user then it would be advisable to have them review the data returned anyway.

**Comment by daspecster** [comment]
@devtayls I've updated the timezone for that zipcode. Thank you for reporting and let me know if you run into any issues!
